# Generated by Django 3.2.7 on 2022-05-04 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('taxable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tfsa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rrsp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_investable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hard_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('checkings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_residence', models.DecimalField(decimal_places=2, max_digits=15)),
                ('auto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('goods', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_personal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mortgages', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumer_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
