# Generated by Django 3.2.7 on 2022-05-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0002_networth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networth',
            old_name='other_personal',
            new_name='other_properties',
        ),
    ]
