# Generated by Django 3.2.7 on 2022-06-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0004_auto_20220524_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='networth',
            name='bitcoin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='ethereum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
