# Generated by Django 3.2.7 on 2022-08-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0007_networth_total_networth'),
    ]

    operations = [
        migrations.AddField(
            model_name='networth',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='total_crypto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='total_investable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='total_liability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='networth',
            name='total_personal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
